version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/abenheni/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/abenheni/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - /home/abenheni/data/wordpress:/usr/share/nginx/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - /home/abenheni/data/wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:42
    volumes:
      - /home/abenheni/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
