version: "2.2"


networks:
  main_network: 

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none 
      device: /home/abenheni/data/mariadb 
      o: bind 

  wordpress_v:
    driver: local
    driver_opts:
      type: none  
      device: /home/abenheni/data/wordpress  
      o: bind 


services:
   
  nginx:
    build: requirements/nginx/ 
    container_name: nginx  
    ports:
      - "443:443" 
    depends_on:
      - wordpress 
    networks:
      - main_network 
    volumes:
      - wordpress_v:/var/www/html 
    restart: on-failure 

  
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb 
    env_file: .env 
    networks:
      - main_network 
    volumes:
      - mariadb_v:/var/lib/mysql 
    restart: on-failure 

 
  wordpress:
    build: requirements/wordpress/ 
    container_name: wordpress 
    env_file: .env 
    depends_on:
      - mariadb 
    networks:
      - main_network 
    volumes:
      - wordpress_v:/var/www/html 
    restart: on-failure 
